### ISSUE TITLE
Only fetches top result?

### ISSUE THREAD

**Issue by JakeAustwick** [postmodern/gscraper#5]
Using the version currently in github repo rather than RubyGems, because the version from RubyGems doesn't include :search_host.

https://gist.github.com/1365681

No matter how i try to query, it just returns the top result over and over.

Any guesses on whats going on?

**Comment by postmodern** [comment]
This is because you are always requesting page 1 of search results. Try requesting pages (1..n).

**Comment by JakeAustwick** [comment]
I'm confused, surely page(1) represents the whole first page, and therefore .urls should be every url on page 1?

Otherwise, how do I get the all the urls on page 1?

**Comment by JakeAustwick** [comment]
I'm fairly sure this isn't working.

q = GScraper::Search.query(:query => 'ruby')
q.each_on_page(2).map do |result|
  p result.title.reverse
end

Output:

"egaugnaL ybuR eht gnitnemucoD :gro.coD-ybuR"
"egaugnaL ybuR eht gnitnemucoD :gro.coD-ybuR"
"egaugnaL ybuR eht gnitnemucoD :gro.coD-ybuR"
"egaugnaL ybuR eht gnitnemucoD :gro.coD-ybuR"
"egaugnaL ybuR eht gnitnemucoD :gro.coD-ybuR"
"egaugnaL ybuR eht gnitnemucoD :gro.coD-ybuR"
"egaugnaL ybuR eht gnitnemucoD :gro.coD-ybuR"
"egaugnaL ybuR eht gnitnemucoD :gro.coD-ybuR"
"egaugnaL ybuR eht gnitnemucoD :gro.coD-ybuR"
"egaugnaL ybuR eht gnitnemucoD :gro.coD-ybuR"

**Comment by postmodern** [comment]
Ah I see, this is a parsing bug.

**Comment by JakeAustwick** [comment]
Tracked the bug down to line 420 in web_query.rb

link = result.at('//h3[@class="r"]/a')

It work's fine with a CSS selector of 'h3.r/a' , so I'm really not sure why this xPath doesn't work.

**Comment by postmodern** [comment]
What version of nokogiri are you using btw? This could be a Nokogiri bug.

**Comment by JakeAustwick** [comment]
Using 1.5.0, check out the pull req I just sent, seems to fix it.
